const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
const POST_PRODUCT_DETAILS = 'POST_PRODUCT_DETAILS';
const PUT_PRODUCT_DETAILS = 'PUT_PRODUCT_DETAILS';
const DELETE_PRODUCT_DETAILS = 'DELETE_PRODUCT_DETAILS';

export { GET_PRODUCT_DETAILS, POST_PRODUCT_DETAILS, PUT_PRODUCT_DETAILS, DELETE_PRODUCT_DETAILS };
